/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './mercedes.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './mercedes.component';
const styles_MercedesComponent:any[] = [i0.styles];
export const RenderType_MercedesComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MercedesComponent,data:{}});
export function View_MercedesComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  mercedes works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_MercedesComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-mercedes',
      ([] as any[]),(null as any),(null as any),(null as any),View_MercedesComponent_0,
      RenderType_MercedesComponent)),i1.ɵdid(1,114688,(null as any),0,i2.MercedesComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MercedesComponentNgFactory:i1.ComponentFactory<i2.MercedesComponent> = i1.ɵccf('app-mercedes',
    i2.MercedesComponent,View_MercedesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL21lcmNlZGVzL21lcmNlZGVzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9zYW1hZ2F0dS9wcm9qZWN0L3NyYy9hcHAvbWVyY2VkZXMvbWVyY2VkZXMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL21lcmNlZGVzL21lcmNlZGVzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL21lcmNlZGVzL21lcmNlZGVzLmNvbXBvbmVudC50cy5NZXJjZWRlc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBtZXJjZWRlcyB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtbWVyY2VkZXM+PC9hcHAtbWVyY2VkZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSw4Q0FFQztNQUFBOzs7b0JDRko7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
