/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './testing.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './testing.component';
import * as i4 from '../data.service';
const styles_TestingComponent:any[] = [i0.styles];
export const RenderType_TestingComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_TestingComponent,data:{}});
function View_TestingComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),16,'ul',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n      '])),(_l()(),i1.ɵeld(2,0,(null as any),(null as any),
      1,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(3,(null as any),['',''])),(_l()(),i1.ɵted(-1,
      (null as any),['\n      '])),(_l()(),i1.ɵeld(5,0,(null as any),(null as any),
      1,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(6,(null as any),['',''])),(_l()(),i1.ɵted(-1,
      (null as any),['\n      '])),(_l()(),i1.ɵeld(8,0,(null as any),(null as any),
      1,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(9,(null as any),['',''])),(_l()(),i1.ɵted(-1,
      (null as any),['\n      '])),(_l()(),i1.ɵeld(11,0,(null as any),(null as any),
      1,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(12,(null as any),['',''])),(_l()(),i1.ɵted(-1,
      (null as any),['\n      '])),(_l()(),i1.ɵeld(14,0,(null as any),(null as any),
      1,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(15,(null as any),['',''])),(_l()(),i1.ɵted(-1,
      (null as any),['\n\n    ']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit.postId;
    _ck(_v,3,0,currVal_0);
    const currVal_1:any = _v.context.$implicit.id;
    _ck(_v,6,0,currVal_1);
    const currVal_2:any = _v.context.$implicit.name;
    _ck(_v,9,0,currVal_2);
    const currVal_3:any = _v.context.$implicit.email;
    _ck(_v,12,0,currVal_3);
    const currVal_4:any = _v.context.$implicit.body;
    _ck(_v,15,0,currVal_4);
  });
}
export function View_TestingComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),9,'div',[['style',
      'text-align:center']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(2,
      0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['\n    Welcome to aTUL SAMAGE\'s portal .\n  '])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n\n  '])),(_l()(),i1.ɵeld(5,0,(null as any),(null as any),4,'body',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵand(16777216,(null as any),
      (null as any),1,(null as any),View_TestingComponent_1)),i1.ɵdid(8,802816,(null as any),
      0,i2.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,
          'ngForOf']},(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n  ']))],
      (_ck,_v) => {
        var _co:i3.TestingComponent = _v.component;
        const currVal_0:any = _co.posts;
        _ck(_v,8,0,currVal_0);
      },(null as any));
}
export function View_TestingComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-testing',
      ([] as any[]),(null as any),(null as any),(null as any),View_TestingComponent_0,
      RenderType_TestingComponent)),i1.ɵdid(1,114688,(null as any),0,i3.TestingComponent,
      [i4.DataService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TestingComponentNgFactory:i1.ComponentFactory<i3.TestingComponent> = i1.ɵccf('app-testing',
    i3.TestingComponent,View_TestingComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL3Rlc3RpbmcvdGVzdGluZy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL3Rlc3RpbmcvdGVzdGluZy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9zYW1hZ2F0dS9wcm9qZWN0L3NyYy9hcHAvdGVzdGluZy90ZXN0aW5nLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL3Rlc3RpbmcvdGVzdGluZy5jb21wb25lbnQudHMuVGVzdGluZ0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgc3R5bGU9XCJ0ZXh0LWFsaWduOmNlbnRlclwiPlxuICA8aDE+XG4gICAgV2VsY29tZSB0byBhVFVMIFNBTUFHRSdzIHBvcnRhbCAuXG4gIDwvaDE+XG5cbiAgPGJvZHk+XG4gICAgPHVsICpuZ0Zvcj1cImxldCBwb3N0IG9mIHBvc3RzXCI+XG4gICAgICA8bGk+e3twb3N0LnBvc3RJZH19PC9saT5cbiAgICAgIDxsaT57e3Bvc3QuaWR9fTwvbGk+XG4gICAgICA8bGk+e3twb3N0Lm5hbWV9fTwvbGk+XG4gICAgICA8bGk+e3twb3N0LmVtYWlsfX08L2xpPlxuICAgICAgPGxpPnt7cG9zdC5ib2R5fX08L2xpPlxuXG4gICAgPC91bD5cbiAgPC9ib2R5PiIsIjxhcHAtdGVzdGluZz48L2FwcC10ZXN0aW5nPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ01JO01BQUEsd0VBQStCO2FBQUEsaUNBQzdCO01BQUE7TUFBQSxnQkFBSSwwQ0FBb0I7TUFBQSw2QkFDeEI7TUFBQTtNQUFBLGdCQUFJLDBDQUFnQjtNQUFBLDZCQUNwQjtNQUFBO01BQUEsZ0JBQUksMENBQWtCO01BQUEsNkJBQ3RCO01BQUE7TUFBQSxnQkFBSSwyQ0FBbUI7TUFBQSw2QkFDdkI7TUFBQTtNQUFBLGdCQUFJLDJDQUFrQjtNQUFBO0lBSmxCO0lBQUE7SUFDQTtJQUFBO0lBQ0E7SUFBQTtJQUNBO0lBQUE7SUFDQTtJQUFBOzs7O29CQVhWO01BQUE7TUFBQSxnQkFBK0IsNENBQzdCO01BQUE7TUFBQSw0Q0FBSTtNQUFBLG1EQUVDO01BQUEsYUFFTDtNQUFBLHdFQUFNO2FBQUEsK0JBQ0o7TUFBQSwrREFBQTtNQUFBO1VBQUEsMkJBT0s7OztRQVBEO1FBQUosV0FBSSxTQUFKOzs7O29CQ05KO01BQUE7aUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
