/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './manupulation.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './manupulation.component';
const styles_ManupulationComponent:any[] = [i0.styles];
export const RenderType_ManupulationComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ManupulationComponent,data:{}});
export function View_ManupulationComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  manupulation works!\n'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n']))],(null as any),(null as any));
}
export function View_ManupulationComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-manupulation',
      ([] as any[]),(null as any),(null as any),(null as any),View_ManupulationComponent_0,
      RenderType_ManupulationComponent)),i1.ɵdid(1,114688,(null as any),0,i2.ManupulationComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ManupulationComponentNgFactory:i1.ComponentFactory<i2.ManupulationComponent> = i1.ɵccf('app-manupulation',
    i2.ManupulationComponent,View_ManupulationComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL21hbnVwdWxhdGlvbi9tYW51cHVsYXRpb24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3NhbWFnYXR1L3Byb2plY3Qvc3JjL2FwcC9tYW51cHVsYXRpb24vbWFudXB1bGF0aW9uLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3NhbWFnYXR1L3Byb2plY3Qvc3JjL2FwcC9tYW51cHVsYXRpb24vbWFudXB1bGF0aW9uLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL21hbnVwdWxhdGlvbi9tYW51cHVsYXRpb24uY29tcG9uZW50LnRzLk1hbnVwdWxhdGlvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBtYW51cHVsYXRpb24gd29ya3MhXG48L3A+XG4iLCI8YXBwLW1hbnVwdWxhdGlvbj48L2FwcC1tYW51cHVsYXRpb24+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSxrREFFQztNQUFBOzs7b0JDRko7TUFBQTtzQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
