/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './page-not-found.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './page-not-found.component';
const styles_PageNotFoundComponent:any[] = [i0.styles];
export const RenderType_PageNotFoundComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PageNotFoundComponent,data:{}});
export function View_PageNotFoundComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  page-not-found works!\n'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n']))],(null as any),(null as any));
}
export function View_PageNotFoundComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-page-not-found',
      ([] as any[]),(null as any),(null as any),(null as any),View_PageNotFoundComponent_0,
      RenderType_PageNotFoundComponent)),i1.ɵdid(1,114688,(null as any),0,i2.PageNotFoundComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PageNotFoundComponentNgFactory:i1.ComponentFactory<i2.PageNotFoundComponent> = i1.ɵccf('app-page-not-found',
    i2.PageNotFoundComponent,View_PageNotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9zYW1hZ2F0dS9wcm9qZWN0L3NyYy9hcHAvcGFnZS1ub3QtZm91bmQvcGFnZS1ub3QtZm91bmQuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL3BhZ2Utbm90LWZvdW5kL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC50cy5QYWdlTm90Rm91bmRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgcGFnZS1ub3QtZm91bmQgd29ya3MhXG48L3A+XG4iLCI8YXBwLXBhZ2Utbm90LWZvdW5kPjwvYXBwLXBhZ2Utbm90LWZvdW5kPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsb0RBRUM7TUFBQTs7O29CQ0ZKO01BQUE7c0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
