/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './football.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './football.component';
const styles_FootballComponent:any[] = [i0.styles];
export const RenderType_FootballComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_FootballComponent,data:{}});
export function View_FootballComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  football works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_FootballComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-football',
      ([] as any[]),(null as any),(null as any),(null as any),View_FootballComponent_0,
      RenderType_FootballComponent)),i1.ɵdid(1,114688,(null as any),0,i2.FootballComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const FootballComponentNgFactory:i1.ComponentFactory<i2.FootballComponent> = i1.ɵccf('app-football',
    i2.FootballComponent,View_FootballComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2Zvb3RiYWxsL2Zvb3RiYWxsLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9zYW1hZ2F0dS9wcm9qZWN0L3NyYy9hcHAvZm9vdGJhbGwvZm9vdGJhbGwuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2Zvb3RiYWxsL2Zvb3RiYWxsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2Zvb3RiYWxsL2Zvb3RiYWxsLmNvbXBvbmVudC50cy5Gb290YmFsbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBmb290YmFsbCB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtZm9vdGJhbGw+PC9hcHAtZm9vdGJhbGw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSw4Q0FFQztNQUFBOzs7b0JDRko7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
