/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './app.component.ngfactory';
import * as i4 from './header/header.component.ngfactory';
import * as i5 from './testing/testing.component.ngfactory';
import * as i6 from './manupulation/manupulation.component.ngfactory';
import * as i7 from './cricket/cricket.component.ngfactory';
import * as i8 from './football/football.component.ngfactory';
import * as i9 from './cactus/cactus.component.ngfactory';
import * as i10 from './mercedes/mercedes.component.ngfactory';
import * as i11 from './home/home.component.ngfactory';
import * as i12 from './tikona/tikona.component.ngfactory';
import * as i13 from './page-not-found/page-not-found.component.ngfactory';
import * as i14 from '@angular/common';
import * as i15 from '@angular/platform-browser';
import * as i16 from '@angular/animations/browser';
import * as i17 from '@angular/platform-browser/animations';
import * as i18 from '@angular/http';
import * as i19 from '@angular/animations';
import * as i20 from '@angular/router';
import * as i21 from './data.service';
import * as i22 from './header/header.component';
import * as i23 from './testing/testing.component';
import * as i24 from './manupulation/manupulation.component';
import * as i25 from './cricket/cricket.component';
import * as i26 from './football/football.component';
import * as i27 from './cactus/cactus.component';
import * as i28 from './mercedes/mercedes.component';
import * as i29 from './home/home.component';
import * as i30 from './tikona/tikona.component';
import * as i31 from './page-not-found/page-not-found.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.AppComponentNgFactory,i4.HeaderComponentNgFactory,i5.TestingComponentNgFactory,
              i6.ManupulationComponentNgFactory,i7.CricketComponentNgFactory,i8.FootballComponentNgFactory,
              i9.CactusComponentNgFactory,i10.MercedesComponentNgFactory,i11.HomeComponentNgFactory,
              i12.TikonaComponentNgFactory,i13.PageNotFoundComponentNgFactory]],[3,
              i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i14.NgLocalization,i14.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i15.DomSanitizer,i15.ɵe,[i14.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i15.DomSanitizer]),i0.ɵmpd(4608,
              i15.HAMMER_GESTURE_CONFIG,i15.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i15.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i15.ɵDomEventsPlugin(p0_0),new i15.ɵKeyEventsPlugin(p1_0),
                    new i15.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i14.DOCUMENT,i14.DOCUMENT,i14.DOCUMENT,i15.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i15.EventManager,i15.EventManager,[i15.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i15.ɵDomSharedStylesHost,i15.ɵDomSharedStylesHost,
              [i14.DOCUMENT]),i0.ɵmpd(4608,i15.ɵDomRendererFactory2,i15.ɵDomRendererFactory2,
              [i15.EventManager,i15.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i16.AnimationDriver,
              i17.ɵc,([] as any[])),i0.ɵmpd(5120,i16.ɵAnimationStyleNormalizer,i17.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i16.ɵAnimationEngine,i17.ɵb,[i16.AnimationDriver,
              i16.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i17.ɵe,
              [i15.ɵDomRendererFactory2,i16.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i15.ɵSharedStylesHost,(null as any),[i15.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i15.Meta,i15.Meta,
              [i14.DOCUMENT]),i0.ɵmpd(4608,i15.Title,i15.Title,[i14.DOCUMENT]),i0.ɵmpd(4608,
              i18.BrowserXhr,i18.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i18.ResponseOptions,
              i18.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i18.XSRFStrategy,
              i18.ɵb,([] as any[])),i0.ɵmpd(4608,i18.XHRBackend,i18.XHRBackend,[i18.BrowserXhr,
              i18.ResponseOptions,i18.XSRFStrategy]),i0.ɵmpd(4608,i18.RequestOptions,
              i18.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i18.Http,i18.ɵc,[i18.XHRBackend,
              i18.RequestOptions]),i0.ɵmpd(4608,i19.AnimationBuilder,i17.ɵBrowserAnimationBuilder,
              [i0.RendererFactory2,i15.DOCUMENT]),i0.ɵmpd(5120,i20.ActivatedRoute,
              i20.ɵf,[i20.Router]),i0.ɵmpd(4608,i20.NoPreloading,i20.NoPreloading,
              ([] as any[])),i0.ɵmpd(6144,i20.PreloadingStrategy,(null as any),[i20.NoPreloading]),
          i0.ɵmpd(135680,i20.RouterPreloader,i20.RouterPreloader,[i20.Router,i0.NgModuleFactoryLoader,
              i0.Compiler,i0.Injector,i20.PreloadingStrategy]),i0.ɵmpd(4608,i20.PreloadAllModules,
              i20.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i20.ROUTER_INITIALIZER,
              i20.ɵi,[i20.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i20.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i21.DataService,i21.DataService,
              [i18.Http]),i0.ɵmpd(512,i14.CommonModule,i14.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i15.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i20.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i20.ɵg,i20.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i15.ɵc(p0_0,p0_1),i20.ɵh(p1_0)];
              },[[2,i15.NgProbeToken],[2,i0.NgProbeToken],i20.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i15.BrowserModule,i15.BrowserModule,[[3,i15.BrowserModule]]),
          i0.ɵmpd(512,i18.HttpModule,i18.HttpModule,([] as any[])),i0.ɵmpd(512,i17.BrowserAnimationsModule,
              i17.BrowserAnimationsModule,([] as any[])),i0.ɵmpd(1024,i20.ɵa,i20.ɵd,
              [[3,i20.Router]]),i0.ɵmpd(512,i20.UrlSerializer,i20.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i20.ChildrenOutletContexts,i20.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i20.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i14.LocationStrategy,i20.ɵc,[i14.PlatformLocation,[2,i14.APP_BASE_HREF],
              i20.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i14.Location,i14.Location,[i14.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i20.ROUTES,() => {
            return [[{path:'',redirectTo:'/home',pathMatch:'full'},{path:'app',component:i2.AppComponent},
                {path:'header',component:i22.HeaderComponent},{path:'testing',component:i23.TestingComponent},
                {path:'manupulation',component:i24.ManupulationComponent},{path:'cricket',
                    component:i25.CricketComponent},{path:'football',component:i26.FootballComponent},
                {path:'cactus',component:i27.CactusComponent},{path:'mercedes',component:i28.MercedesComponent},
                {path:'home',component:i29.HomeComponent},{path:'tikona',component:i30.TikonaComponent},
                {path:'**',component:i31.PageNotFoundComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i20.Router,i20.ɵe,[i0.ApplicationRef,i20.UrlSerializer,
              i20.ChildrenOutletContexts,i14.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i20.ROUTES,i20.ROUTER_CONFIGURATION,[2,i20.UrlHandlingStrategy],
              [2,i20.RouteReuseStrategy]]),i0.ɵmpd(512,i20.RouterModule,i20.RouterModule,
              [[2,i20.ɵa],[2,i20.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
