/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './cactus.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './cactus.component';
const styles_CactusComponent:any[] = [i0.styles];
export const RenderType_CactusComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_CactusComponent,data:{}});
export function View_CactusComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  cactus works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_CactusComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-cactus',
      ([] as any[]),(null as any),(null as any),(null as any),View_CactusComponent_0,
      RenderType_CactusComponent)),i1.ɵdid(1,114688,(null as any),0,i2.CactusComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const CactusComponentNgFactory:i1.ComponentFactory<i2.CactusComponent> = i1.ɵccf('app-cactus',
    i2.CactusComponent,View_CactusComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2NhY3R1cy9jYWN0dXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3NhbWFnYXR1L3Byb2plY3Qvc3JjL2FwcC9jYWN0dXMvY2FjdHVzLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3NhbWFnYXR1L3Byb2plY3Qvc3JjL2FwcC9jYWN0dXMvY2FjdHVzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2NhY3R1cy9jYWN0dXMuY29tcG9uZW50LnRzLkNhY3R1c0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBjYWN0dXMgd29ya3MhXG48L3A+XG4iLCI8YXBwLWNhY3R1cz48L2FwcC1jYWN0dXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSw0Q0FFQztNQUFBOzs7b0JDRko7TUFBQTtnQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
