/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './cricket.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './cricket.component';
const styles_CricketComponent:any[] = [i0.styles];
export const RenderType_CricketComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_CricketComponent,data:{}});
export function View_CricketComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  cricket works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_CricketComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-cricket',
      ([] as any[]),(null as any),(null as any),(null as any),View_CricketComponent_0,
      RenderType_CricketComponent)),i1.ɵdid(1,114688,(null as any),0,i2.CricketComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const CricketComponentNgFactory:i1.ComponentFactory<i2.CricketComponent> = i1.ɵccf('app-cricket',
    i2.CricketComponent,View_CricketComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2NyaWNrZXQvY3JpY2tldC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2NyaWNrZXQvY3JpY2tldC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9zYW1hZ2F0dS9wcm9qZWN0L3NyYy9hcHAvY3JpY2tldC9jcmlja2V0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvc2FtYWdhdHUvcHJvamVjdC9zcmMvYXBwL2NyaWNrZXQvY3JpY2tldC5jb21wb25lbnQudHMuQ3JpY2tldENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBjcmlja2V0IHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1jcmlja2V0PjwvYXBwLWNyaWNrZXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSw2Q0FFQztNQUFBOzs7b0JDRko7TUFBQTtpQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
